export const RISK_RULES = Object.freeze({
  modelVersion: "1.0.0",
  scoreRange: Object.freeze({ min: 0, max: 100 }),
  levels: Object.freeze([
    Object.freeze({
      id: "low",
      min: 0,
      max: 19,
      title: "ریسک پایین",
      shortTitle: "پایین",
      icon: "●",
      color: "green",
      explanation: "بر اساس داده‌های واردشده، عوامل شناخته‌شده فشار زیادی بر اتصال وارد نمی‌کنند.",
      recommendation:
        "بر اساس اطلاعات واردشده، ریسک پایین ارزیابی می‌شود؛ برای اطمینان بیشتر، زمان و شرایط رسمی را با ایرلاین یا فرودگاه تطبیق دهید.",
    }),
    Object.freeze({
      id: "medium",
      min: 20,
      max: 39,
      title: "ریسک متوسط",
      shortTitle: "متوسط",
      icon: "●",
      color: "yellow",
      explanation: "برخی عوامل یا اطلاعات نامشخص می‌توانند اجرای اتصال را دشوارتر کنند.",
      recommendation:
        "برخی از جزئیات این اتصال نیازمند بررسی است؛ تطبیق حداقل زمان اتصال و الزامات بار و ترانزیت با ایرلاین یا فرودگاه توصیه می‌شود.",
    }),
    Object.freeze({
      id: "high",
      min: 40,
      max: 64,
      title: "ریسک بالا",
      shortTitle: "بالا",
      icon: "●",
      color: "orange",
      explanation: "حاشیه امن محدود است یا چند عامل مهم، اتصال را پرریسک می‌کنند.",
      recommendation:
        "چند عامل مهم در این اتصال وجود دارد؛ توصیه می‌شود پیش از سفر، زمان اتصال و شرایط ترانزیت با ایرلاین یا فرودگاه تطبیق داده شود.",
    }),
    Object.freeze({
      id: "very-high",
      min: 65,
      max: 100,
      title: "ریسک بسیار بالا",
      shortTitle: "بسیار بالا",
      icon: "●",
      color: "red",
      explanation: "بر اساس اطلاعات فعلی، احتمال از دست رفتن پرواز بعدی یا اختلال جدی قابل توجه است.",
      recommendation:
        "عوامل متعددی فشار زیادی بر این اتصال وارد می‌کنند؛ توصیه می‌شود جزئیات مسیر، بار و شرایط ترانزیت پیش از سفر با ایرلاین و فرودگاه تأیید شود.",
    }),
  ]),
  delayScenarios: Object.freeze([15, 30, 45, 60, 90, 120]),
  timePenaltyBands: Object.freeze([
    Object.freeze({ belowMinutes: 30, points: 76, label: "کمتر از ۳۰ دقیقه" }),
    Object.freeze({ belowMinutes: 60, points: 62, label: "کمتر از یک ساعت" }),
    Object.freeze({ belowMinutes: 90, points: 50, label: "کمتر از یک ساعت و نیم" }),
    Object.freeze({ belowMinutes: 120, points: 40, label: "کمتر از دو ساعت" }),
    Object.freeze({ belowMinutes: 180, points: 28, label: "کمتر از سه ساعت" }),
    Object.freeze({ belowMinutes: 240, points: 17, label: "کمتر از چهار ساعت" }),
  ]),
  mctMinutes: Object.freeze({
    sameAirportAirsideSingleTicket: 90,
    sameAirportAirsideUnclear: 120,
    landside: 240,
    separateTicketOrSelfTransfer: 240,
    sameCityAirportChange: 150,
    differentCityAirportChange: 480,
    immigrationYes: 45,
    immigrationUnknown: 15,
    terminalChangeYes: 30,
    terminalChangeUnknown: 10,
    baggageRecheckYes: 45,
    baggageUnknown: 15,
    checkInYes: 60,
    checkInUnknown: 15,
    securityYes: 30,
    securityUnknown: 10,
  }),
  factorPoints: Object.freeze({
    baseEstimateUncertainty: 4,
    sameCityAirportChange: 29,
    differentCityAirportChange: 40,
    airlineDifferent: 4,
    airlineUnknown: 2,
    separateTicket: 18,
    ticketUnknown: 3,
    selfTransfer: 16,
    landside: 8,
    transferUnknown: 2,
    baggageRecheck: 12,
    baggageUnknown: 2,
    checkInRequired: 10,
    checkInUnknown: 2,
    immigrationRequired: 7,
    immigrationUnknown: 1,
    terminalChange: 8,
    terminalUnknown: 1,
    securityRecheck: 6,
    securityUnknown: 1,
    overnightConnection: 4,
    longLayover12Hours: 3,
    longLayover24Hours: 5,
    contradictoryAirportAnswer: 3,
    missingFlightNumber: 1,
    ambiguousLocalTime: 4,
  }),
  relativeTimePenalty: Object.freeze({
    belowEstimatedMct: 15,
    belowMctPlus30: 9,
    belowMctPlus60: 4,
  }),
  timeThresholds: Object.freeze({
    mctMarginMinutes: Object.freeze({ limited: 30, modest: 60 }),
    longLayoverMinutes: Object.freeze({ extended: 12 * 60, veryLong: 24 * 60 }),
  }),
});

export const RISK_MODEL_NOTICE =
  "حداقل زمان اتصال و امتیازها برآورد داخلیِ محافظه‌کارانه‌اند؛ MCT رسمی یا تضمین امکان ترانزیت نیستند.";
